name: Markdown to Word

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
 
    - name: Install Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install pandoc
 
    - name: Convert Markdown to Word
      run: |
        mkdir output
        cd output
        mkdir docs
        cd ..
        for file in docs/*.md; do
          pandoc "$file" -o "output/${file%.md}.docx"
        done
 
    - name: Save converted Word files
      uses: actions/upload-artifact@v2
      with:
        name: word-files
        path: output
